# Generated by Django 4.1.7 on 2023-05-24 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'ProductGallerys', 'verbose_name_plural': 'product gallery'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['created'], 'verbose_name': 'Productss', 'verbose_name_plural': 'Products'},
        ),
    ]
