# Generated by Django 4.1.7 on 2023-03-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_img',
            field=models.ImageField(blank=True, null=True, upload_to='category/'),
        ),
    ]
