# Generated by Django 4.1.7 on 2023-05-14 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_payment_translation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='translation',
            new_name='transaction',
        ),
    ]
